# Generated by Django 4.2.13 on 2024-06-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_filedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='value',
            field=models.TextField(),
        ),
    ]
